name: 自動清理舊工作流

on:
  schedule:
    - cron: '0 2 1 * *'  # 每月1日 UTC 2:00 (台灣時間 10:00)
  workflow_dispatch:
    inputs:
      days_threshold:
        description: '保留天數'
        default: '60'
      dry_run:
        description: '僅預覽模式'
        default: 'true'
        type: boolean

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 清理舊標籤
        run: |
          DAYS="${{ github.event.inputs.days_threshold || '60' }}"
          DRY_RUN="${{ github.event.inputs.dry_run || 'true' }}"
          THRESHOLD=$(date -d "$DAYS days ago" +%Y-%m-%d)
          
          echo "保留 $DAYS 天內的標籤，閾值日期: $THRESHOLD"
          echo "預覽模式: $DRY_RUN"
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          for tag in $(git tag); do
            TAG_DATE=$(git log -1 --format=%ai "$tag" | cut -d' ' -f1)
            if [[ "$TAG_DATE" < "$THRESHOLD" ]]; then
              if [ "$DRY_RUN" = "true" ]; then
                echo "[預覽] 將刪除標籤: $tag (創建於 $TAG_DATE)"
              else
                echo "刪除標籤: $tag (創建於 $TAG_DATE)"
                git tag -d "$tag"
                git push --delete origin "$tag" || echo "無法刪除遠程標籤 $tag"
              fi
            fi
          done
          
      - name: 清理舊工作流
        run: |
          DAYS="${{ github.event.inputs.days_threshold || '60' }}"
          DRY_RUN="${{ github.event.inputs.dry_run || 'true' }}"
          THRESHOLD=$(date -d "$DAYS days ago" +%s)
          
          echo "檢查過期工作流..."
          
          for file in workflows/*.json; do
            if [ -f "$file" ]; then
              FILE_DATE=$(stat -c %Y "$file")
              if [ "$FILE_DATE" -lt "$THRESHOLD" ]; then
                if [ "$DRY_RUN" = "true" ]; then
                  echo "[預覽] 將刪除: $file"
                else
                  echo "刪除: $file"
                  rm "$file"
                fi
              fi
            fi
          done
          
      - name: 提交變更
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          if git status --porcelain | grep -q "workflows/"; then
            git add workflows/
            git commit -m "chore: 清理舊工作流檔案"
            git push
          else
            echo "無需提交變更"
          fi
